services:
  postgres:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "htrancinvania"
      POSTGRES_PASSWORD: "12345678"
      POSTGRES_DB: "htrancinvania"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: